### ISSUE TITLE
Document Usage via `debug` Sourceset

### ISSUE THREAD

**Issue by commonsguy** [jasonwyatt/Android-DebugPort#1]
As a long-ago fan of Beanshell, kudos for using it!

However, given the name and role, ideally we would only add this library into our `debug` builds. At best, your existing instructions will add bloat to `release` builds without some custom ProGuard rules. At worst, this might exacerbate other security issues (e.g., another hack leveraging Beanshell to run arbitrary scripts).

For example, you could:

- use `debugCompile` instead of `compile` for the dependency
- have a custom `Application` class in the `debug` sourceset that starts the service
- have a custom manifest in the `debug` sourceset that uses the custom `Application` and adds the `<service>`

Then, a `release` build will be unaffected.

**Comment by jasonwyatt** [comment]
Great point!

I had to implement something similar to the `debugCompile` approach you listed above in order to use Android-DebugPort with my day job's app.  I will work on some documentation updates to explain how to go about doing that.

**Comment by jasonwyatt** [comment]
I've created a no-op version of the library here: https://github.com/jasonwyatt/Android-DebugPort-NOOP and updated the README.md to provide instructions for using the no-op version with releaseCompile (and the regular version with debugCompile/testCompile)
