### ISSUE TITLE
Make DebugPort a full drop-in library

### ISSUE THREAD

**Issue by nohum** [jasonwyatt/Android-DebugPort#11]
Hey!
Thanks for that awesome library. I think it would be nice to make this library behave like a drop-in, e.g. just write

```
debugCompile 'com.github.jasonwyatt:Android-DebugPort:1.1.0'
```

in your build.gradle, without any needs for `noop`-versions and manual initialization in the `Application` class.

Getting the context and initialization can be done the `Google Firebase`-way: https://firebase.googleblog.com/2016/12/how-does-firebase-initialize-on-android.html

And including the `<service>` can be done via including the library as `AAR` and then via manifest merger. What do you think about that?

**Comment by jasonwyatt** [comment]
@nohum That's a great idea! One thing to consider though: what would the best way be to allow people to start/stop the debugport server?  I think it's important that it's not just always on (imagine developing your app at a cafe: you might not want to expose your app's innards to the wild)

**Comment by nohum** [comment]
Having `debugCompile 'com.github.jasonwyatt:Android-DebugPort:1.1.0'` in your gradle file while debugging in a cafe with the current implementation would also leave the ports open to the wild ;)

But to tackle this problem in certain, i would e.g. call  `DebugPortService.start()` in the content provider and then make it the developers responsibility to call `stop()` or `start()` further down the road. One useful addition may be a boolean resource item controlling the auto-`start()` functionality if the app has been opened initially.

**Comment by jasonwyatt** [comment]
It actually doesn't start the telnet servers until you call `start()`,
which is what I was getting at.

What would you think of a notification that lets you start/stop the
servers? If it's going to be drop-in, I think it shouldn't require any
actual code to enable/disable the ports.

**Comment by nohum** [comment]
Actually, I think the notification is a good idea but I wouldn't remove the code-entry points to stop or start it if somebody is eager to do that on his own responsibility. :)

**Comment by jasonwyatt** [comment]
Thanks again for the great idea! [2.0.0](https://github.com/jasonwyatt/Android-DebugPort/releases/tag/2.0.0) has been released and makes the project a drop-in tool.
